// <auto-generated />
namespace ConsoleApplication1.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Addedproperty3 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Addedproperty3));
        
        string IMigrationMetadata.Id
        {
            get { return "201604200813181_Added property 3"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
